/**
 * MASAI Service Discovery API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ServiceDiscovery);
  }
}(this, function(expect, ServiceDiscovery) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ServiceDiscovery.Location();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Location', function() {
    it('should create an instance of Location', function() {
      // uncomment below and update the code to test Location
      //var instane = new ServiceDiscovery.Location();
      //expect(instance).to.be.a(ServiceDiscovery.Location);
    });

    it('should have the property minLatitude (base name: "minLatitude")', function() {
      // uncomment below and update the code to test the property minLatitude
      //var instane = new ServiceDiscovery.Location();
      //expect(instance).to.be();
    });

    it('should have the property minLongitude (base name: "minLongitude")', function() {
      // uncomment below and update the code to test the property minLongitude
      //var instane = new ServiceDiscovery.Location();
      //expect(instance).to.be();
    });

    it('should have the property maxLatitude (base name: "maxLatitude")', function() {
      // uncomment below and update the code to test the property maxLatitude
      //var instane = new ServiceDiscovery.Location();
      //expect(instance).to.be();
    });

    it('should have the property maxLongitude (base name: "maxLongitude")', function() {
      // uncomment below and update the code to test the property maxLongitude
      //var instane = new ServiceDiscovery.Location();
      //expect(instance).to.be();
    });

    it('should have the property countries (base name: "countries")', function() {
      // uncomment below and update the code to test the property countries
      //var instane = new ServiceDiscovery.Location();
      //expect(instance).to.be();
    });

    it('should have the property cities (base name: "cities")', function() {
      // uncomment below and update the code to test the property cities
      //var instane = new ServiceDiscovery.Location();
      //expect(instance).to.be();
    });

  });

}));
