/**
 * MASAI Service Discovery API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ServiceDiscovery);
  }
}(this, function(expect, ServiceDiscovery) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ServiceDiscovery.SearchResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SearchResponse', function() {
    it('should create an instance of SearchResponse', function() {
      // uncomment below and update the code to test SearchResponse
      //var instane = new ServiceDiscovery.SearchResponse();
      //expect(instance).to.be.a(ServiceDiscovery.SearchResponse);
    });

    it('should have the property serviceDescription (base name: "serviceDescription")', function() {
      // uncomment below and update the code to test the property serviceDescription
      //var instane = new ServiceDiscovery.SearchResponse();
      //expect(instance).to.be();
    });

    it('should have the property timers (base name: "timers")', function() {
      // uncomment below and update the code to test the property timers
      //var instane = new ServiceDiscovery.SearchResponse();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new ServiceDiscovery.SearchResponse();
      //expect(instance).to.be();
    });

    it('should have the property message (base name: "message")', function() {
      // uncomment below and update the code to test the property message
      //var instane = new ServiceDiscovery.SearchResponse();
      //expect(instance).to.be();
    });

  });

}));
