/* 
 * MASAI Service Discovery API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ServiceDiscovery.Api;
using ServiceDiscovery.Model;
using ServiceDiscovery.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ServiceDiscovery.Test
{
    /// <summary>
    ///  Class for testing Data
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DataTests
    {
        // TODO uncomment below to declare an instance variable for Data
        //private Data instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Data
            //instance = new Data();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Data
        /// </summary>
        [Test]
        public void DataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Data
            //Assert.IsInstanceOfType<Data> (instance, "variable 'instance' is a Data");
        }


        /// <summary>
        /// Test the property 'PlanConditions'
        /// </summary>
        [Test]
        public void PlanConditionsTest()
        {
            // TODO unit test for the property 'PlanConditions'
        }
        /// <summary>
        /// Test the property 'Swagger'
        /// </summary>
        [Test]
        public void SwaggerTest()
        {
            // TODO unit test for the property 'Swagger'
        }
        /// <summary>
        /// Test the property 'Properties'
        /// </summary>
        [Test]
        public void PropertiesTest()
        {
            // TODO unit test for the property 'Properties'
        }
        /// <summary>
        /// Test the property 'Contact'
        /// </summary>
        [Test]
        public void ContactTest()
        {
            // TODO unit test for the property 'Contact'
        }
        /// <summary>
        /// Test the property 'Maintainers'
        /// </summary>
        [Test]
        public void MaintainersTest()
        {
            // TODO unit test for the property 'Maintainers'
        }
        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Test]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }
        /// <summary>
        /// Test the property 'IntegrationMode'
        /// </summary>
        [Test]
        public void IntegrationModeTest()
        {
            // TODO unit test for the property 'IntegrationMode'
        }
        /// <summary>
        /// Test the property 'LevelOfService'
        /// </summary>
        [Test]
        public void LevelOfServiceTest()
        {
            // TODO unit test for the property 'LevelOfService'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Image'
        /// </summary>
        [Test]
        public void ImageTest()
        {
            // TODO unit test for the property 'Image'
        }
        /// <summary>
        /// Test the property 'BaseURL'
        /// </summary>
        [Test]
        public void BaseURLTest()
        {
            // TODO unit test for the property 'BaseURL'
        }
        /// <summary>
        /// Test the property 'HumanURL'
        /// </summary>
        [Test]
        public void HumanURLTest()
        {
            // TODO unit test for the property 'HumanURL'
        }
        /// <summary>
        /// Test the property 'AppName'
        /// </summary>
        [Test]
        public void AppNameTest()
        {
            // TODO unit test for the property 'AppName'
        }
        /// <summary>
        /// Test the property 'PackageName'
        /// </summary>
        [Test]
        public void PackageNameTest()
        {
            // TODO unit test for the property 'PackageName'
        }
        /// <summary>
        /// Test the property 'DeeplinkURL'
        /// </summary>
        [Test]
        public void DeeplinkURLTest()
        {
            // TODO unit test for the property 'DeeplinkURL'
        }
        /// <summary>
        /// Test the property 'PlanConditionsUrl'
        /// </summary>
        [Test]
        public void PlanConditionsUrlTest()
        {
            // TODO unit test for the property 'PlanConditionsUrl'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Test]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
        /// <summary>
        /// Test the property 'SignatureKey'
        /// </summary>
        [Test]
        public void SignatureKeyTest()
        {
            // TODO unit test for the property 'SignatureKey'
        }
        /// <summary>
        /// Test the property 'Authoritative'
        /// </summary>
        [Test]
        public void AuthoritativeTest()
        {
            // TODO unit test for the property 'Authoritative'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

    }

}
