/* 
 * MASAI Service Discovery API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ServiceDiscovery.Api;
using ServiceDiscovery.Model;
using ServiceDiscovery.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ServiceDiscovery.Test
{
    /// <summary>
    ///  Class for testing DiscoveryRequestServiceType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DiscoveryRequestServiceTypeTests
    {
        // TODO uncomment below to declare an instance variable for DiscoveryRequestServiceType
        //private DiscoveryRequestServiceType instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DiscoveryRequestServiceType
            //instance = new DiscoveryRequestServiceType();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DiscoveryRequestServiceType
        /// </summary>
        [Test]
        public void DiscoveryRequestServiceTypeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DiscoveryRequestServiceType
            //Assert.IsInstanceOfType<DiscoveryRequestServiceType> (instance, "variable 'instance' is a DiscoveryRequestServiceType");
        }


        /// <summary>
        /// Test the property 'Discovery'
        /// </summary>
        [Test]
        public void DiscoveryTest()
        {
            // TODO unit test for the property 'Discovery'
        }
        /// <summary>
        /// Test the property 'Booking'
        /// </summary>
        [Test]
        public void BookingTest()
        {
            // TODO unit test for the property 'Booking'
        }
        /// <summary>
        /// Test the property 'Reschedule'
        /// </summary>
        [Test]
        public void RescheduleTest()
        {
            // TODO unit test for the property 'Reschedule'
        }
        /// <summary>
        /// Test the property 'Info'
        /// </summary>
        [Test]
        public void InfoTest()
        {
            // TODO unit test for the property 'Info'
        }
        /// <summary>
        /// Test the property 'All'
        /// </summary>
        [Test]
        public void AllTest()
        {
            // TODO unit test for the property 'All'
        }

    }

}
