/* 
 * MASAI Service Discovery API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ServiceDiscovery.Api;
using ServiceDiscovery.Model;
using ServiceDiscovery.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ServiceDiscovery.Test
{
    /// <summary>
    ///  Class for testing JsonXmlObject
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class JsonXmlObjectTests
    {
        // TODO uncomment below to declare an instance variable for JsonXmlObject
        //private JsonXmlObject instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of JsonXmlObject
            //instance = new JsonXmlObject();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of JsonXmlObject
        /// </summary>
        [Test]
        public void JsonXmlObjectInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" JsonXmlObject
            //Assert.IsInstanceOfType<JsonXmlObject> (instance, "variable 'instance' is a JsonXmlObject");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Wrapped'
        /// </summary>
        [Test]
        public void WrappedTest()
        {
            // TODO unit test for the property 'Wrapped'
        }
        /// <summary>
        /// Test the property '_Namespace'
        /// </summary>
        [Test]
        public void _NamespaceTest()
        {
            // TODO unit test for the property '_Namespace'
        }
        /// <summary>
        /// Test the property 'Prefix'
        /// </summary>
        [Test]
        public void PrefixTest()
        {
            // TODO unit test for the property 'Prefix'
        }
        /// <summary>
        /// Test the property 'Attribute'
        /// </summary>
        [Test]
        public void AttributeTest()
        {
            // TODO unit test for the property 'Attribute'
        }

    }

}
