/* 
 * MASAI Service Discovery API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ServiceDiscovery.Api;
using ServiceDiscovery.Model;
using ServiceDiscovery.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ServiceDiscovery.Test
{
    /// <summary>
    ///  Class for testing JsonExpectedSchema
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class JsonExpectedSchemaTests
    {
        // TODO uncomment below to declare an instance variable for JsonExpectedSchema
        //private JsonExpectedSchema instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of JsonExpectedSchema
            //instance = new JsonExpectedSchema();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of JsonExpectedSchema
        /// </summary>
        [Test]
        public void JsonExpectedSchemaInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" JsonExpectedSchema
            //Assert.IsInstanceOfType<JsonExpectedSchema> (instance, "variable 'instance' is a JsonExpectedSchema");
        }


        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Schema'
        /// </summary>
        [Test]
        public void SchemaTest()
        {
            // TODO unit test for the property 'Schema'
        }

    }

}
