/* 
 * MASAI Service Discovery API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ServiceDiscovery.Api;
using ServiceDiscovery.Model;
using ServiceDiscovery.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ServiceDiscovery.Test
{
    /// <summary>
    ///  Class for testing Location
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LocationTests
    {
        // TODO uncomment below to declare an instance variable for Location
        //private Location instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Location
            //instance = new Location();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Location
        /// </summary>
        [Test]
        public void LocationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Location
            //Assert.IsInstanceOfType<Location> (instance, "variable 'instance' is a Location");
        }


        /// <summary>
        /// Test the property 'MinLatitude'
        /// </summary>
        [Test]
        public void MinLatitudeTest()
        {
            // TODO unit test for the property 'MinLatitude'
        }
        /// <summary>
        /// Test the property 'MinLongitude'
        /// </summary>
        [Test]
        public void MinLongitudeTest()
        {
            // TODO unit test for the property 'MinLongitude'
        }
        /// <summary>
        /// Test the property 'MaxLatitude'
        /// </summary>
        [Test]
        public void MaxLatitudeTest()
        {
            // TODO unit test for the property 'MaxLatitude'
        }
        /// <summary>
        /// Test the property 'MaxLongitude'
        /// </summary>
        [Test]
        public void MaxLongitudeTest()
        {
            // TODO unit test for the property 'MaxLongitude'
        }
        /// <summary>
        /// Test the property 'Countries'
        /// </summary>
        [Test]
        public void CountriesTest()
        {
            // TODO unit test for the property 'Countries'
        }
        /// <summary>
        /// Test the property 'Cities'
        /// </summary>
        [Test]
        public void CitiesTest()
        {
            // TODO unit test for the property 'Cities'
        }

    }

}
