/* 
 * MASAI Service Discovery API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ServiceDiscovery.Api;
using ServiceDiscovery.Model;
using ServiceDiscovery.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ServiceDiscovery.Test
{
    /// <summary>
    ///  Class for testing Rating
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RatingTests
    {
        // TODO uncomment below to declare an instance variable for Rating
        //private Rating instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Rating
            //instance = new Rating();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Rating
        /// </summary>
        [Test]
        public void RatingInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Rating
            //Assert.IsInstanceOfType<Rating> (instance, "variable 'instance' is a Rating");
        }


        /// <summary>
        /// Test the property 'MinRating'
        /// </summary>
        [Test]
        public void MinRatingTest()
        {
            // TODO unit test for the property 'MinRating'
        }
        /// <summary>
        /// Test the property 'MaxRating'
        /// </summary>
        [Test]
        public void MaxRatingTest()
        {
            // TODO unit test for the property 'MaxRating'
        }

    }

}
