/* 
 * MASAI Service Discovery API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ServiceDiscovery.Api;
using ServiceDiscovery.Model;
using ServiceDiscovery.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ServiceDiscovery.Test
{
    /// <summary>
    ///  Class for testing SearchResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SearchResponseTests
    {
        // TODO uncomment below to declare an instance variable for SearchResponse
        //private SearchResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SearchResponse
            //instance = new SearchResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SearchResponse
        /// </summary>
        [Test]
        public void SearchResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SearchResponse
            //Assert.IsInstanceOfType<SearchResponse> (instance, "variable 'instance' is a SearchResponse");
        }


        /// <summary>
        /// Test the property 'ServiceDescription'
        /// </summary>
        [Test]
        public void ServiceDescriptionTest()
        {
            // TODO unit test for the property 'ServiceDescription'
        }
        /// <summary>
        /// Test the property 'Timers'
        /// </summary>
        [Test]
        public void TimersTest()
        {
            // TODO unit test for the property 'Timers'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

    }

}
