/* 
 * MASAI Service Discovery API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ServiceDiscovery.Api;
using ServiceDiscovery.Model;
using ServiceDiscovery.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ServiceDiscovery.Test
{
    /// <summary>
    ///  Class for testing SwaggerSecurityScheme
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SwaggerSecuritySchemeTests
    {
        // TODO uncomment below to declare an instance variable for SwaggerSecurityScheme
        //private SwaggerSecurityScheme instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SwaggerSecurityScheme
            //instance = new SwaggerSecurityScheme();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SwaggerSecurityScheme
        /// </summary>
        [Test]
        public void SwaggerSecuritySchemeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SwaggerSecurityScheme
            //Assert.IsInstanceOfType<SwaggerSecurityScheme> (instance, "variable 'instance' is a SwaggerSecurityScheme");
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property '_In'
        /// </summary>
        [Test]
        public void _InTest()
        {
            // TODO unit test for the property '_In'
        }
        /// <summary>
        /// Test the property 'Flow'
        /// </summary>
        [Test]
        public void FlowTest()
        {
            // TODO unit test for the property 'Flow'
        }
        /// <summary>
        /// Test the property 'AuthorizationUrl'
        /// </summary>
        [Test]
        public void AuthorizationUrlTest()
        {
            // TODO unit test for the property 'AuthorizationUrl'
        }
        /// <summary>
        /// Test the property 'TokenUrl'
        /// </summary>
        [Test]
        public void TokenUrlTest()
        {
            // TODO unit test for the property 'TokenUrl'
        }
        /// <summary>
        /// Test the property 'Scopes'
        /// </summary>
        [Test]
        public void ScopesTest()
        {
            // TODO unit test for the property 'Scopes'
        }

    }

}
