/* 
 * MASAI Service Discovery API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ServiceDiscovery.Api;
using ServiceDiscovery.Model;
using ServiceDiscovery.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ServiceDiscovery.Test
{
    /// <summary>
    ///  Class for testing SwaggerOperation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SwaggerOperationTests
    {
        // TODO uncomment below to declare an instance variable for SwaggerOperation
        //private SwaggerOperation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SwaggerOperation
            //instance = new SwaggerOperation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SwaggerOperation
        /// </summary>
        [Test]
        public void SwaggerOperationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SwaggerOperation
            //Assert.IsInstanceOfType<SwaggerOperation> (instance, "variable 'instance' is a SwaggerOperation");
        }


        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Test]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }
        /// <summary>
        /// Test the property 'Summary'
        /// </summary>
        [Test]
        public void SummaryTest()
        {
            // TODO unit test for the property 'Summary'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'ExternalDocs'
        /// </summary>
        [Test]
        public void ExternalDocsTest()
        {
            // TODO unit test for the property 'ExternalDocs'
        }
        /// <summary>
        /// Test the property 'OperationId'
        /// </summary>
        [Test]
        public void OperationIdTest()
        {
            // TODO unit test for the property 'OperationId'
        }
        /// <summary>
        /// Test the property 'Schemes'
        /// </summary>
        [Test]
        public void SchemesTest()
        {
            // TODO unit test for the property 'Schemes'
        }
        /// <summary>
        /// Test the property 'Consumes'
        /// </summary>
        [Test]
        public void ConsumesTest()
        {
            // TODO unit test for the property 'Consumes'
        }
        /// <summary>
        /// Test the property 'Produces'
        /// </summary>
        [Test]
        public void ProducesTest()
        {
            // TODO unit test for the property 'Produces'
        }
        /// <summary>
        /// Test the property 'Parameters'
        /// </summary>
        [Test]
        public void ParametersTest()
        {
            // TODO unit test for the property 'Parameters'
        }
        /// <summary>
        /// Test the property 'Responses'
        /// </summary>
        [Test]
        public void ResponsesTest()
        {
            // TODO unit test for the property 'Responses'
        }
        /// <summary>
        /// Test the property 'Deprecated'
        /// </summary>
        [Test]
        public void DeprecatedTest()
        {
            // TODO unit test for the property 'Deprecated'
        }
        /// <summary>
        /// Test the property 'Security'
        /// </summary>
        [Test]
        public void SecurityTest()
        {
            // TODO unit test for the property 'Security'
        }

    }

}
