#import <Foundation/Foundation.h>
#import "MASAIObject.h"

/**
* MASAI Service Discovery API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "MASAIJsonExpectedSchema.h"
#import "MASAIJsonSchema4.h"
@protocol MASAIJsonExpectedSchema;
@class MASAIJsonExpectedSchema;
@protocol MASAIJsonSchema4;
@class MASAIJsonSchema4;



@protocol MASAISwaggerResponse
@end

@interface MASAISwaggerResponse : MASAIObject

/* Gets or sets the response's description. [optional]
 */
@property(nonatomic) NSString* _description;
/* Gets or sets the response schema. [optional]
 */
@property(nonatomic) MASAIJsonSchema4* schema;
/* Gets or sets the headers. [optional]
 */
@property(nonatomic) NSDictionary<MASAIJsonSchema4>* headers;
/* Sets a value indicating whether the response can be null (use IsNullable() to get a parameter's nullability). [optional]
 */
@property(nonatomic) NSNumber* xNullable;
/* Gets or sets the expected child schemas of the base schema (can be used for generating enhanced typings/documentation). [optional]
 */
@property(nonatomic) NSArray<MASAIJsonExpectedSchema>* xExpectedSchemas;

@end
