#import <Foundation/Foundation.h>
#import "MASAIObject.h"

/**
* MASAI Service Discovery API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "MASAISwaggerOperation.h"
@protocol MASAISwaggerOperation;
@class MASAISwaggerOperation;



@protocol MASAISwaggerDocumentPaths
@end

@interface MASAISwaggerDocumentPaths : MASAIObject


@property(nonatomic) MASAISwaggerOperation* undefined;

@property(nonatomic) MASAISwaggerOperation* get;

@property(nonatomic) MASAISwaggerOperation* post;

@property(nonatomic) MASAISwaggerOperation* put;

@property(nonatomic) MASAISwaggerOperation* delete;

@property(nonatomic) MASAISwaggerOperation* options;

@property(nonatomic) MASAISwaggerOperation* head;

@property(nonatomic) MASAISwaggerOperation* patch;

@end
