#import <Foundation/Foundation.h>
#import "MASAIObject.h"

/**
* MASAI Service Discovery API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol MASAISwaggerExternalDocumentation
@end

@interface MASAISwaggerExternalDocumentation : MASAIObject

/* Gets or sets the description. [optional]
 */
@property(nonatomic) NSString* _description;
/* Gets or sets the documentation URL. [optional]
 */
@property(nonatomic) NSString* url;

@end
