#import <Foundation/Foundation.h>
#import "MASAIObject.h"

/**
* MASAI Service Discovery API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol MASAISwaggerSecurityScheme
@end

@interface MASAISwaggerSecurityScheme : MASAIObject

/* Gets or sets the type of the security scheme. 
 */
@property(nonatomic) NSString* type;
/* Gets or sets the short description for security scheme. [optional]
 */
@property(nonatomic) NSString* _description;
/* Gets or sets the name of the header or query parameter to be used to transmit the API key. [optional]
 */
@property(nonatomic) NSString* name;
/* Gets or sets the type of the API key. [optional]
 */
@property(nonatomic) NSString* in;
/* Gets or sets the used by the OAuth2 security scheme. [optional]
 */
@property(nonatomic) NSString* flow;
/* Gets or sets the authorization URL to be used for this flow. [optional]
 */
@property(nonatomic) NSString* authorizationUrl;
/* Gets or sets the token URL to be used for this flow. . [optional]
 */
@property(nonatomic) NSString* tokenUrl;
/* Gets the available scopes for the OAuth2 security scheme. [optional]
 */
@property(nonatomic) NSDictionary<NSString*, NSString*>* scopes;

@end
