#import <Foundation/Foundation.h>
#import "MASAIObject.h"

/**
* MASAI Service Discovery API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol MASAIContact
@end

@interface MASAIContact : MASAIObject

/* Gets or Sets FullName [optional]
 */
@property(nonatomic) NSString* fullName;
/* Gets or Sets Email [optional]
 */
@property(nonatomic) NSString* email;
/* Gets or Sets Url [optional]
 */
@property(nonatomic) NSString* url;
/* Gets or Sets Organization [optional]
 */
@property(nonatomic) NSString* organization;
/* Gets or Sets Address [optional]
 */
@property(nonatomic) NSString* address;
/* Gets or Sets Telephone [optional]
 */
@property(nonatomic) NSString* telephone;
/* Gets or Sets Twitter [optional]
 */
@property(nonatomic) NSString* twitter;
/* Gets or Sets Github [optional]
 */
@property(nonatomic) NSString* github;
/* Gets or Sets Photo [optional]
 */
@property(nonatomic) NSString* photo;
/* Gets or Sets VCard [optional]
 */
@property(nonatomic) NSString* vCard;

@end
