#import <Foundation/Foundation.h>
#import "MASAIObject.h"

/**
* MASAI Service Discovery API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "MASAIData.h"
@protocol MASAIData;
@class MASAIData;



@protocol MASAISearchResponse
@end

@interface MASAISearchResponse : MASAIObject

/* Service information [optional]
 */
@property(nonatomic) NSArray<MASAIData>* serviceDescription;
/* Timer information for each search engine [optional]
 */
@property(nonatomic) NSArray<NSString*>* timers;
/* Status information [optional]
 */
@property(nonatomic) NSString* status;
/* Service error message [optional]
 */
@property(nonatomic) NSString* message;

@end
