#import <Foundation/Foundation.h>
#import "MASAIObject.h"

/**
* MASAI Service Discovery API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "MASAIJsonSchema4.h"
#import "MASAIJsonXmlObject.h"
@protocol MASAIJsonSchema4;
@class MASAIJsonSchema4;
@protocol MASAIJsonXmlObject;
@class MASAIJsonXmlObject;



@protocol MASAISwaggerParameter
@end

@interface MASAISwaggerParameter : MASAIObject


@property(nonatomic) NSString* schema;

@property(nonatomic) NSString* _id;

@property(nonatomic) NSString* title;

@property(nonatomic) NSObject* type;

@property(nonatomic) NSString* discriminator;
/* Gets or sets the name. [optional]
 */
@property(nonatomic) NSString* name;
/* Gets or sets the kind of the parameter. [optional]
 */
@property(nonatomic) NSString* in;
/* Gets or sets a value indicating whether the parameter is required (default: false). [optional]
 */
@property(nonatomic) NSNumber* required;
/* Gets or sets a value indicating whether passing empty-valued parameters is allowed (default: false). [optional]
 */
@property(nonatomic) NSNumber* allowEmptyValue;
/* Gets or sets the schema which is only available when {NSwag.SwaggerParameter.Kind} == body. [optional]
 */
@property(nonatomic) MASAIJsonSchema4* schema;
/* Sets a value indicating whether the parameter can be null (use IsNullable() to get a parameter's nullability). [optional]
 */
@property(nonatomic) NSNumber* xNullable;
/* Gets or sets the format of the array if type array is used. [optional]
 */
@property(nonatomic) NSString* collectionFormat;

@property(nonatomic) NSString* _description;

@property(nonatomic) NSString* schemaReferencePath;

@property(nonatomic) NSString* format;

@property(nonatomic) NSObject* _default;

@property(nonatomic) NSNumber* multipleOf;

@property(nonatomic) NSNumber* maximum;

@property(nonatomic) NSNumber* exclusiveMaximum;

@property(nonatomic) NSNumber* minimum;

@property(nonatomic) NSNumber* exclusiveMinimum;

@property(nonatomic) NSNumber* maxLength;

@property(nonatomic) NSNumber* minLength;

@property(nonatomic) NSString* pattern;

@property(nonatomic) NSNumber* maxItems;

@property(nonatomic) NSNumber* minItems;

@property(nonatomic) NSNumber* uniqueItems;

@property(nonatomic) NSNumber* maxProperties;

@property(nonatomic) NSNumber* minProperties;

@property(nonatomic) MASAIJsonXmlObject* xml;

@property(nonatomic) MASAIJsonSchema4* not;

@property(nonatomic) NSObject* additionalItems;

@property(nonatomic) NSObject* additionalProperties;

@property(nonatomic) NSObject* items;

@property(nonatomic) NSDictionary<MASAIJsonSchema4>* properties;

@property(nonatomic) NSDictionary<MASAIJsonSchema4>* patternProperties;

@property(nonatomic) NSDictionary<MASAIJsonSchema4>* definitions;

@property(nonatomic) NSArray<NSString*>* xEnumNames;

@property(nonatomic) NSArray<NSObject*>* _enum;

@property(nonatomic) NSArray<MASAIJsonSchema4>* allOf;

@property(nonatomic) NSArray<MASAIJsonSchema4>* anyOf;

@property(nonatomic) NSArray<MASAIJsonSchema4>* oneOf;

@end
