#import <Foundation/Foundation.h>
#import "MASAIObject.h"

/**
* MASAI Service Discovery API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol MASAIProperties
@end

@interface MASAIProperties : MASAIObject

/* Type of propery [optional]
 */
@property(nonatomic) NSString* type;
/* URL of property [optional]
 */
@property(nonatomic) NSString* url;

@end
