#import <Foundation/Foundation.h>
#import "MASAIObject.h"

/**
* MASAI Service Discovery API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "MASAIDiscoveryRequest.h"
@protocol MASAIDiscoveryRequest;
@class MASAIDiscoveryRequest;



@protocol MASAISearchCriteria
@end

@interface MASAISearchCriteria : MASAIObject

/* Environment to search services 
 */
@property(nonatomic) NSString* environment;
/* List containing each type of service to look for 
 */
@property(nonatomic) NSArray<MASAIDiscoveryRequest>* serviceSearchCriteria;

@end
