/**
 * MASAI Service Discovery API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['DiscoverySearchEngine/ApiClient', 'DiscoverySearchEngine/DiscoverySearchEngine/DiscoveryRequestServiceType', 'DiscoverySearchEngine/DiscoverySearchEngine/Location', 'DiscoverySearchEngine/DiscoverySearchEngine/Price', 'DiscoverySearchEngine/DiscoverySearchEngine/Rating'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DiscoveryRequestServiceType'), require('./Location'), require('./Price'), require('./Rating'));
  } else {
    // Browser globals (root is window)
    if (!root.DiscoverySearchEngine) {
      root.DiscoverySearchEngine = {};
    }
    root.DiscoverySearchEngine.DiscoveryRequest = factory(root.DiscoverySearchEngine.ApiClient, root.DiscoverySearchEngine.DiscoveryRequestServiceType, root.DiscoverySearchEngine.Location, root.DiscoverySearchEngine.Price, root.DiscoverySearchEngine.Rating);
  }
}(this, function(ApiClient, DiscoveryRequestServiceType, Location, Price, Rating) {
  'use strict';




  /**
   * The DiscoveryRequest model module.
   * @module DiscoverySearchEngine/DiscoverySearchEngine/DiscoveryRequest
   * @version v1
   */

  /**
   * Constructs a new <code>DiscoveryRequest</code>.
   * Information containing the service description you want to search for
   * @alias module:DiscoverySearchEngine/DiscoverySearchEngine/DiscoveryRequest
   * @class
   * @param groupOfModule {String} Group of module information (taxi|accomodation|train|flight|bus|tourism|all|car_sharing|bike_sharing|train_station_elevator|train_station_parking|car_rental|restaurant|coworkingspace|public_transport)
   * @param serviceType {module:DiscoverySearchEngine/DiscoverySearchEngine/DiscoveryRequestServiceType} 
   */
  var exports = function(groupOfModule, serviceType) {
    var _this = this;




    _this['groupOfModule'] = groupOfModule;


    _this['serviceType'] = serviceType;
  };

  /**
   * Constructs a <code>DiscoveryRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:DiscoverySearchEngine/DiscoverySearchEngine/DiscoveryRequest} obj Optional instance to populate.
   * @return {module:DiscoverySearchEngine/DiscoverySearchEngine/DiscoveryRequest} The populated <code>DiscoveryRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('location')) {
        obj['location'] = Location.constructFromObject(data['location']);
      }
      if (data.hasOwnProperty('price')) {
        obj['price'] = Price.constructFromObject(data['price']);
      }
      if (data.hasOwnProperty('rating')) {
        obj['rating'] = Rating.constructFromObject(data['rating']);
      }
      if (data.hasOwnProperty('groupOfModule')) {
        obj['groupOfModule'] = ApiClient.convertToType(data['groupOfModule'], 'String');
      }
      if (data.hasOwnProperty('accessKey')) {
        obj['accessKey'] = ApiClient.convertToType(data['accessKey'], 'String');
      }
      if (data.hasOwnProperty('providers')) {
        obj['providers'] = ApiClient.convertToType(data['providers'], ['String']);
      }
      if (data.hasOwnProperty('serviceType')) {
        obj['serviceType'] = DiscoveryRequestServiceType.constructFromObject(data['serviceType']);
      }
    }
    return obj;
  }

  /**
   * Location information
   * @member {module:DiscoverySearchEngine/DiscoverySearchEngine/Location} location
   */
  exports.prototype['location'] = undefined;
  /**
   * Price range information
   * @member {module:DiscoverySearchEngine/DiscoverySearchEngine/Price} price
   */
  exports.prototype['price'] = undefined;
  /**
   * Rating range information
   * @member {module:DiscoverySearchEngine/DiscoverySearchEngine/Rating} rating
   */
  exports.prototype['rating'] = undefined;
  /**
   * Group of module information (taxi|accomodation|train|flight|bus|tourism|all|car_sharing|bike_sharing|train_station_elevator|train_station_parking|car_rental|restaurant|coworkingspace|public_transport)
   * @member {String} groupOfModule
   */
  exports.prototype['groupOfModule'] = undefined;
  /**
   * Google Custom Search Engine Access Key
   * @member {String} accessKey
   */
  exports.prototype['accessKey'] = undefined;
  /**
   * Search engines selected to search for (If none is selected, then the Service Discovery will search on all search engines)
   * @member {Array.<module:DiscoverySearchEngine/DiscoverySearchEngine/DiscoveryRequest.ProvidersEnum>} providers
   */
  exports.prototype['providers'] = undefined;
  /**
   * @member {module:DiscoverySearchEngine/DiscoverySearchEngine/DiscoveryRequestServiceType} serviceType
   */
  exports.prototype['serviceType'] = undefined;


  /**
   * Allowed values for the <code>providers</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ProvidersEnum = {
    /**
     * value: "apis"
     * @const
     */
    "apis": "apis",
    /**
     * value: "google"
     * @const
     */
    "google": "google",
    /**
     * value: "ckan"
     * @const
     */
    "ckan": "ckan"  };


  return exports;
}));


