/**
 * MASAI Service Discovery API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['DiscoverySearchEngine/ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DiscoverySearchEngine) {
      root.DiscoverySearchEngine = {};
    }
    root.DiscoverySearchEngine.DiscoveryRequestServiceType = factory(root.DiscoverySearchEngine.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The DiscoveryRequestServiceType model module.
   * @module DiscoverySearchEngine/DiscoverySearchEngine/DiscoveryRequestServiceType
   * @version v1
   */

  /**
   * Constructs a new <code>DiscoveryRequestServiceType</code>.
   * Combination between the Group of Service and the Integration Mode (E.g.: Search for applications that performs the discovery process &#x3D;&amp;gt; \&quot;discovery\&quot;:\&quot;api\&quot;)
   * @alias module:DiscoverySearchEngine/DiscoverySearchEngine/DiscoveryRequestServiceType
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>DiscoveryRequestServiceType</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:DiscoverySearchEngine/DiscoverySearchEngine/DiscoveryRequestServiceType} obj Optional instance to populate.
   * @return {module:DiscoverySearchEngine/DiscoverySearchEngine/DiscoveryRequestServiceType} The populated <code>DiscoveryRequestServiceType</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('discovery')) {
        obj['discovery'] = ApiClient.convertToType(data['discovery'], 'String');
      }
      if (data.hasOwnProperty('booking')) {
        obj['booking'] = ApiClient.convertToType(data['booking'], 'String');
      }
      if (data.hasOwnProperty('reschedule')) {
        obj['reschedule'] = ApiClient.convertToType(data['reschedule'], 'String');
      }
      if (data.hasOwnProperty('info')) {
        obj['info'] = ApiClient.convertToType(data['info'], 'String');
      }
      if (data.hasOwnProperty('all')) {
        obj['all'] = ApiClient.convertToType(data['all'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:DiscoverySearchEngine/DiscoverySearchEngine/DiscoveryRequestServiceType.DiscoveryEnum} discovery
   */
  exports.prototype['discovery'] = undefined;
  /**
   * @member {module:DiscoverySearchEngine/DiscoverySearchEngine/DiscoveryRequestServiceType.BookingEnum} booking
   */
  exports.prototype['booking'] = undefined;
  /**
   * @member {module:DiscoverySearchEngine/DiscoverySearchEngine/DiscoveryRequestServiceType.RescheduleEnum} reschedule
   */
  exports.prototype['reschedule'] = undefined;
  /**
   * @member {module:DiscoverySearchEngine/DiscoverySearchEngine/DiscoveryRequestServiceType.InfoEnum} info
   */
  exports.prototype['info'] = undefined;
  /**
   * @member {module:DiscoverySearchEngine/DiscoverySearchEngine/DiscoveryRequestServiceType.AllEnum} all
   */
  exports.prototype['all'] = undefined;


  /**
   * Allowed values for the <code>discovery</code> property.
   * @enum {String}
   * @readonly
   */
  exports.DiscoveryEnum = {
    /**
     * value: "web"
     * @const
     */
    "web": "web",
    /**
     * value: "app"
     * @const
     */
    "app": "app",
    /**
     * value: "api"
     * @const
     */
    "api": "api",
    /**
     * value: "deeplink"
     * @const
     */
    "deeplink": "deeplink",
    /**
     * value: "all"
     * @const
     */
    "all": "all",
    /**
     * value: "ConciergeWeb"
     * @const
     */
    "ConciergeWeb": "ConciergeWeb",
    /**
     * value: "ConciergeApp"
     * @const
     */
    "ConciergeApp": "ConciergeApp",
    /**
     * value: "ConciergeAPI"
     * @const
     */
    "ConciergeAPI": "ConciergeAPI",
    /**
     * value: "ConciergeDeeplink"
     * @const
     */
    "ConciergeDeeplink": "ConciergeDeeplink",
    /**
     * value: "widget"
     * @const
     */
    "widget": "widget",
    /**
     * value: "ConciergeWidget"
     * @const
     */
    "ConciergeWidget": "ConciergeWidget",
    /**
     * value: "ConciergeDialog"
     * @const
     */
    "ConciergeDialog": "ConciergeDialog",
    /**
     * value: "chatserver"
     * @const
     */
    "chatserver": "chatserver"  };

  /**
   * Allowed values for the <code>booking</code> property.
   * @enum {String}
   * @readonly
   */
  exports.BookingEnum = {
    /**
     * value: "web"
     * @const
     */
    "web": "web",
    /**
     * value: "app"
     * @const
     */
    "app": "app",
    /**
     * value: "api"
     * @const
     */
    "api": "api",
    /**
     * value: "deeplink"
     * @const
     */
    "deeplink": "deeplink",
    /**
     * value: "all"
     * @const
     */
    "all": "all",
    /**
     * value: "ConciergeWeb"
     * @const
     */
    "ConciergeWeb": "ConciergeWeb",
    /**
     * value: "ConciergeApp"
     * @const
     */
    "ConciergeApp": "ConciergeApp",
    /**
     * value: "ConciergeAPI"
     * @const
     */
    "ConciergeAPI": "ConciergeAPI",
    /**
     * value: "ConciergeDeeplink"
     * @const
     */
    "ConciergeDeeplink": "ConciergeDeeplink",
    /**
     * value: "widget"
     * @const
     */
    "widget": "widget",
    /**
     * value: "ConciergeWidget"
     * @const
     */
    "ConciergeWidget": "ConciergeWidget",
    /**
     * value: "ConciergeDialog"
     * @const
     */
    "ConciergeDialog": "ConciergeDialog",
    /**
     * value: "chatserver"
     * @const
     */
    "chatserver": "chatserver"  };

  /**
   * Allowed values for the <code>reschedule</code> property.
   * @enum {String}
   * @readonly
   */
  exports.RescheduleEnum = {
    /**
     * value: "web"
     * @const
     */
    "web": "web",
    /**
     * value: "app"
     * @const
     */
    "app": "app",
    /**
     * value: "api"
     * @const
     */
    "api": "api",
    /**
     * value: "deeplink"
     * @const
     */
    "deeplink": "deeplink",
    /**
     * value: "all"
     * @const
     */
    "all": "all",
    /**
     * value: "ConciergeWeb"
     * @const
     */
    "ConciergeWeb": "ConciergeWeb",
    /**
     * value: "ConciergeApp"
     * @const
     */
    "ConciergeApp": "ConciergeApp",
    /**
     * value: "ConciergeAPI"
     * @const
     */
    "ConciergeAPI": "ConciergeAPI",
    /**
     * value: "ConciergeDeeplink"
     * @const
     */
    "ConciergeDeeplink": "ConciergeDeeplink",
    /**
     * value: "widget"
     * @const
     */
    "widget": "widget",
    /**
     * value: "ConciergeWidget"
     * @const
     */
    "ConciergeWidget": "ConciergeWidget",
    /**
     * value: "ConciergeDialog"
     * @const
     */
    "ConciergeDialog": "ConciergeDialog",
    /**
     * value: "chatserver"
     * @const
     */
    "chatserver": "chatserver"  };

  /**
   * Allowed values for the <code>info</code> property.
   * @enum {String}
   * @readonly
   */
  exports.InfoEnum = {
    /**
     * value: "web"
     * @const
     */
    "web": "web",
    /**
     * value: "app"
     * @const
     */
    "app": "app",
    /**
     * value: "api"
     * @const
     */
    "api": "api",
    /**
     * value: "deeplink"
     * @const
     */
    "deeplink": "deeplink",
    /**
     * value: "all"
     * @const
     */
    "all": "all",
    /**
     * value: "ConciergeWeb"
     * @const
     */
    "ConciergeWeb": "ConciergeWeb",
    /**
     * value: "ConciergeApp"
     * @const
     */
    "ConciergeApp": "ConciergeApp",
    /**
     * value: "ConciergeAPI"
     * @const
     */
    "ConciergeAPI": "ConciergeAPI",
    /**
     * value: "ConciergeDeeplink"
     * @const
     */
    "ConciergeDeeplink": "ConciergeDeeplink",
    /**
     * value: "widget"
     * @const
     */
    "widget": "widget",
    /**
     * value: "ConciergeWidget"
     * @const
     */
    "ConciergeWidget": "ConciergeWidget",
    /**
     * value: "ConciergeDialog"
     * @const
     */
    "ConciergeDialog": "ConciergeDialog",
    /**
     * value: "chatserver"
     * @const
     */
    "chatserver": "chatserver"  };

  /**
   * Allowed values for the <code>all</code> property.
   * @enum {String}
   * @readonly
   */
  exports.AllEnum = {
    /**
     * value: "web"
     * @const
     */
    "web": "web",
    /**
     * value: "app"
     * @const
     */
    "app": "app",
    /**
     * value: "api"
     * @const
     */
    "api": "api",
    /**
     * value: "deeplink"
     * @const
     */
    "deeplink": "deeplink",
    /**
     * value: "all"
     * @const
     */
    "all": "all",
    /**
     * value: "ConciergeWeb"
     * @const
     */
    "ConciergeWeb": "ConciergeWeb",
    /**
     * value: "ConciergeApp"
     * @const
     */
    "ConciergeApp": "ConciergeApp",
    /**
     * value: "ConciergeAPI"
     * @const
     */
    "ConciergeAPI": "ConciergeAPI",
    /**
     * value: "ConciergeDeeplink"
     * @const
     */
    "ConciergeDeeplink": "ConciergeDeeplink",
    /**
     * value: "widget"
     * @const
     */
    "widget": "widget",
    /**
     * value: "ConciergeWidget"
     * @const
     */
    "ConciergeWidget": "ConciergeWidget",
    /**
     * value: "ConciergeDialog"
     * @const
     */
    "ConciergeDialog": "ConciergeDialog",
    /**
     * value: "chatserver"
     * @const
     */
    "chatserver": "chatserver"  };


  return exports;
}));


