/**
 * MASAI Service Discovery API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['DiscoverySearchEngine/ApiClient', 'DiscoverySearchEngine/DiscoverySearchEngine/JsonSchema4', 'DiscoverySearchEngine/DiscoverySearchEngine/JsonXmlObject'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./JsonSchema4'), require('./JsonXmlObject'));
  } else {
    // Browser globals (root is window)
    if (!root.DiscoverySearchEngine) {
      root.DiscoverySearchEngine = {};
    }
    root.DiscoverySearchEngine.JsonSchema4 = factory(root.DiscoverySearchEngine.ApiClient, root.DiscoverySearchEngine.JsonSchema4, root.DiscoverySearchEngine.JsonXmlObject);
  }
}(this, function(ApiClient, JsonSchema4, JsonXmlObject) {
  'use strict';




  /**
   * The JsonSchema4 model module.
   * @module DiscoverySearchEngine/DiscoverySearchEngine/JsonSchema4
   * @version v1
   */

  /**
   * Constructs a new <code>JsonSchema4</code>.
   * @alias module:DiscoverySearchEngine/DiscoverySearchEngine/JsonSchema4
   * @class
   */
  var exports = function() {
    var _this = this;





































  };

  /**
   * Constructs a <code>JsonSchema4</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:DiscoverySearchEngine/DiscoverySearchEngine/JsonSchema4} obj Optional instance to populate.
   * @return {module:DiscoverySearchEngine/DiscoverySearchEngine/JsonSchema4} The populated <code>JsonSchema4</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('$schema')) {
        obj['$schema'] = ApiClient.convertToType(data['$schema'], 'String');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], Object);
      }
      if (data.hasOwnProperty('discriminator')) {
        obj['discriminator'] = ApiClient.convertToType(data['discriminator'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('schemaReferencePath')) {
        obj['schemaReferencePath'] = ApiClient.convertToType(data['schemaReferencePath'], 'String');
      }
      if (data.hasOwnProperty('format')) {
        obj['format'] = ApiClient.convertToType(data['format'], 'String');
      }
      if (data.hasOwnProperty('default')) {
        obj['default'] = ApiClient.convertToType(data['default'], Object);
      }
      if (data.hasOwnProperty('multipleOf')) {
        obj['multipleOf'] = ApiClient.convertToType(data['multipleOf'], 'Number');
      }
      if (data.hasOwnProperty('maximum')) {
        obj['maximum'] = ApiClient.convertToType(data['maximum'], 'Number');
      }
      if (data.hasOwnProperty('exclusiveMaximum')) {
        obj['exclusiveMaximum'] = ApiClient.convertToType(data['exclusiveMaximum'], 'Boolean');
      }
      if (data.hasOwnProperty('minimum')) {
        obj['minimum'] = ApiClient.convertToType(data['minimum'], 'Number');
      }
      if (data.hasOwnProperty('exclusiveMinimum')) {
        obj['exclusiveMinimum'] = ApiClient.convertToType(data['exclusiveMinimum'], 'Boolean');
      }
      if (data.hasOwnProperty('maxLength')) {
        obj['maxLength'] = ApiClient.convertToType(data['maxLength'], 'Number');
      }
      if (data.hasOwnProperty('minLength')) {
        obj['minLength'] = ApiClient.convertToType(data['minLength'], 'Number');
      }
      if (data.hasOwnProperty('pattern')) {
        obj['pattern'] = ApiClient.convertToType(data['pattern'], 'String');
      }
      if (data.hasOwnProperty('maxItems')) {
        obj['maxItems'] = ApiClient.convertToType(data['maxItems'], 'Number');
      }
      if (data.hasOwnProperty('minItems')) {
        obj['minItems'] = ApiClient.convertToType(data['minItems'], 'Number');
      }
      if (data.hasOwnProperty('uniqueItems')) {
        obj['uniqueItems'] = ApiClient.convertToType(data['uniqueItems'], 'Boolean');
      }
      if (data.hasOwnProperty('maxProperties')) {
        obj['maxProperties'] = ApiClient.convertToType(data['maxProperties'], 'Number');
      }
      if (data.hasOwnProperty('minProperties')) {
        obj['minProperties'] = ApiClient.convertToType(data['minProperties'], 'Number');
      }
      if (data.hasOwnProperty('xml')) {
        obj['xml'] = JsonXmlObject.constructFromObject(data['xml']);
      }
      if (data.hasOwnProperty('not')) {
        obj['not'] = JsonSchema4.constructFromObject(data['not']);
      }
      if (data.hasOwnProperty('additionalItems')) {
        obj['additionalItems'] = ApiClient.convertToType(data['additionalItems'], Object);
      }
      if (data.hasOwnProperty('additionalProperties')) {
        obj['additionalProperties'] = ApiClient.convertToType(data['additionalProperties'], Object);
      }
      if (data.hasOwnProperty('items')) {
        obj['items'] = ApiClient.convertToType(data['items'], Object);
      }
      if (data.hasOwnProperty('required')) {
        obj['required'] = ApiClient.convertToType(data['required'], ['String']);
      }
      if (data.hasOwnProperty('properties')) {
        obj['properties'] = ApiClient.convertToType(data['properties'], {'String': JsonSchema4});
      }
      if (data.hasOwnProperty('patternProperties')) {
        obj['patternProperties'] = ApiClient.convertToType(data['patternProperties'], {'String': JsonSchema4});
      }
      if (data.hasOwnProperty('definitions')) {
        obj['definitions'] = ApiClient.convertToType(data['definitions'], {'String': JsonSchema4});
      }
      if (data.hasOwnProperty('x-enumNames')) {
        obj['x-enumNames'] = ApiClient.convertToType(data['x-enumNames'], ['String']);
      }
      if (data.hasOwnProperty('enum')) {
        obj['enum'] = ApiClient.convertToType(data['enum'], [Object]);
      }
      if (data.hasOwnProperty('allOf')) {
        obj['allOf'] = ApiClient.convertToType(data['allOf'], [JsonSchema4]);
      }
      if (data.hasOwnProperty('anyOf')) {
        obj['anyOf'] = ApiClient.convertToType(data['anyOf'], [JsonSchema4]);
      }
      if (data.hasOwnProperty('oneOf')) {
        obj['oneOf'] = ApiClient.convertToType(data['oneOf'], [JsonSchema4]);
      }
    }
    return obj;
  }

  /**
   * @member {String} $schema
   */
  exports.prototype['$schema'] = undefined;
  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * @member {Object} type
   */
  exports.prototype['type'] = undefined;
  /**
   * @member {String} discriminator
   */
  exports.prototype['discriminator'] = undefined;
  /**
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * @member {String} schemaReferencePath
   */
  exports.prototype['schemaReferencePath'] = undefined;
  /**
   * @member {String} format
   */
  exports.prototype['format'] = undefined;
  /**
   * @member {Object} default
   */
  exports.prototype['default'] = undefined;
  /**
   * @member {Number} multipleOf
   */
  exports.prototype['multipleOf'] = undefined;
  /**
   * @member {Number} maximum
   */
  exports.prototype['maximum'] = undefined;
  /**
   * @member {Boolean} exclusiveMaximum
   */
  exports.prototype['exclusiveMaximum'] = undefined;
  /**
   * @member {Number} minimum
   */
  exports.prototype['minimum'] = undefined;
  /**
   * @member {Boolean} exclusiveMinimum
   */
  exports.prototype['exclusiveMinimum'] = undefined;
  /**
   * @member {Number} maxLength
   */
  exports.prototype['maxLength'] = undefined;
  /**
   * @member {Number} minLength
   */
  exports.prototype['minLength'] = undefined;
  /**
   * @member {String} pattern
   */
  exports.prototype['pattern'] = undefined;
  /**
   * @member {Number} maxItems
   */
  exports.prototype['maxItems'] = undefined;
  /**
   * @member {Number} minItems
   */
  exports.prototype['minItems'] = undefined;
  /**
   * @member {Boolean} uniqueItems
   */
  exports.prototype['uniqueItems'] = undefined;
  /**
   * @member {Number} maxProperties
   */
  exports.prototype['maxProperties'] = undefined;
  /**
   * @member {Number} minProperties
   */
  exports.prototype['minProperties'] = undefined;
  /**
   * @member {module:DiscoverySearchEngine/DiscoverySearchEngine/JsonXmlObject} xml
   */
  exports.prototype['xml'] = undefined;
  /**
   * @member {module:DiscoverySearchEngine/DiscoverySearchEngine/JsonSchema4} not
   */
  exports.prototype['not'] = undefined;
  /**
   * @member {Object} additionalItems
   */
  exports.prototype['additionalItems'] = undefined;
  /**
   * @member {Object} additionalProperties
   */
  exports.prototype['additionalProperties'] = undefined;
  /**
   * @member {Object} items
   */
  exports.prototype['items'] = undefined;
  /**
   * @member {Array.<String>} required
   */
  exports.prototype['required'] = undefined;
  /**
   * @member {Object.<String, module:DiscoverySearchEngine/DiscoverySearchEngine/JsonSchema4>} properties
   */
  exports.prototype['properties'] = undefined;
  /**
   * @member {Object.<String, module:DiscoverySearchEngine/DiscoverySearchEngine/JsonSchema4>} patternProperties
   */
  exports.prototype['patternProperties'] = undefined;
  /**
   * @member {Object.<String, module:DiscoverySearchEngine/DiscoverySearchEngine/JsonSchema4>} definitions
   */
  exports.prototype['definitions'] = undefined;
  /**
   * @member {Array.<String>} x-enumNames
   */
  exports.prototype['x-enumNames'] = undefined;
  /**
   * @member {Array.<Object>} enum
   */
  exports.prototype['enum'] = undefined;
  /**
   * @member {Array.<module:DiscoverySearchEngine/DiscoverySearchEngine/JsonSchema4>} allOf
   */
  exports.prototype['allOf'] = undefined;
  /**
   * @member {Array.<module:DiscoverySearchEngine/DiscoverySearchEngine/JsonSchema4>} anyOf
   */
  exports.prototype['anyOf'] = undefined;
  /**
   * @member {Array.<module:DiscoverySearchEngine/DiscoverySearchEngine/JsonSchema4>} oneOf
   */
  exports.prototype['oneOf'] = undefined;



  return exports;
}));


