/**
 * MASAI Service Discovery API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['DiscoverySearchEngine/ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DiscoverySearchEngine) {
      root.DiscoverySearchEngine = {};
    }
    root.DiscoverySearchEngine.Rating = factory(root.DiscoverySearchEngine.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Rating model module.
   * @module DiscoverySearchEngine/DiscoverySearchEngine/Rating
   * @version v1
   */

  /**
   * Constructs a new <code>Rating</code>.
   * Rating range information
   * @alias module:DiscoverySearchEngine/DiscoverySearchEngine/Rating
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>Rating</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:DiscoverySearchEngine/DiscoverySearchEngine/Rating} obj Optional instance to populate.
   * @return {module:DiscoverySearchEngine/DiscoverySearchEngine/Rating} The populated <code>Rating</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('minRating')) {
        obj['minRating'] = ApiClient.convertToType(data['minRating'], 'Number');
      }
      if (data.hasOwnProperty('maxRating')) {
        obj['maxRating'] = ApiClient.convertToType(data['maxRating'], 'Number');
      }
    }
    return obj;
  }

  /**
   * Minimum rating
   * @member {Number} minRating
   */
  exports.prototype['minRating'] = undefined;
  /**
   * Maximum rating
   * @member {Number} maxRating
   */
  exports.prototype['maxRating'] = undefined;



  return exports;
}));


