/**
 * MASAI Service Discovery API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['DiscoverySearchEngine/ApiClient', 'DiscoverySearchEngine/DiscoverySearchEngine/SwaggerContact', 'DiscoverySearchEngine/DiscoverySearchEngine/SwaggerLicense'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SwaggerContact'), require('./SwaggerLicense'));
  } else {
    // Browser globals (root is window)
    if (!root.DiscoverySearchEngine) {
      root.DiscoverySearchEngine = {};
    }
    root.DiscoverySearchEngine.SwaggerInfo = factory(root.DiscoverySearchEngine.ApiClient, root.DiscoverySearchEngine.SwaggerContact, root.DiscoverySearchEngine.SwaggerLicense);
  }
}(this, function(ApiClient, SwaggerContact, SwaggerLicense) {
  'use strict';




  /**
   * The SwaggerInfo model module.
   * @module DiscoverySearchEngine/DiscoverySearchEngine/SwaggerInfo
   * @version v1
   */

  /**
   * Constructs a new <code>SwaggerInfo</code>.
   * The web service description.
   * @alias module:DiscoverySearchEngine/DiscoverySearchEngine/SwaggerInfo
   * @class
   * @param title {String} Gets or sets the title.
   * @param version {String} Gets or sets the API version.
   */
  var exports = function(title, version) {
    var _this = this;

    _this['title'] = title;




    _this['version'] = version;
  };

  /**
   * Constructs a <code>SwaggerInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:DiscoverySearchEngine/DiscoverySearchEngine/SwaggerInfo} obj Optional instance to populate.
   * @return {module:DiscoverySearchEngine/DiscoverySearchEngine/SwaggerInfo} The populated <code>SwaggerInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('title')) {
        obj['title'] = ApiClient.convertToType(data['title'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('termsOfService')) {
        obj['termsOfService'] = ApiClient.convertToType(data['termsOfService'], 'String');
      }
      if (data.hasOwnProperty('contact')) {
        obj['contact'] = SwaggerContact.constructFromObject(data['contact']);
      }
      if (data.hasOwnProperty('license')) {
        obj['license'] = SwaggerLicense.constructFromObject(data['license']);
      }
      if (data.hasOwnProperty('version')) {
        obj['version'] = ApiClient.convertToType(data['version'], 'String');
      }
    }
    return obj;
  }

  /**
   * Gets or sets the title.
   * @member {String} title
   */
  exports.prototype['title'] = undefined;
  /**
   * Gets or sets the description.
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * Gets or sets the terms of service.
   * @member {String} termsOfService
   */
  exports.prototype['termsOfService'] = undefined;
  /**
   * Gets or sets the contact information.
   * @member {module:DiscoverySearchEngine/DiscoverySearchEngine/SwaggerContact} contact
   */
  exports.prototype['contact'] = undefined;
  /**
   * Gets or sets the license information.
   * @member {module:DiscoverySearchEngine/DiscoverySearchEngine/SwaggerLicense} license
   */
  exports.prototype['license'] = undefined;
  /**
   * Gets or sets the API version.
   * @member {String} version
   */
  exports.prototype['version'] = undefined;



  return exports;
}));


