/**
 * MASAI Service Discovery API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['DiscoverySearchEngine/ApiClient', 'DiscoverySearchEngine/DiscoverySearchEngine/SwaggerExternalDocumentation'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SwaggerExternalDocumentation'));
  } else {
    // Browser globals (root is window)
    if (!root.DiscoverySearchEngine) {
      root.DiscoverySearchEngine = {};
    }
    root.DiscoverySearchEngine.SwaggerTag = factory(root.DiscoverySearchEngine.ApiClient, root.DiscoverySearchEngine.SwaggerExternalDocumentation);
  }
}(this, function(ApiClient, SwaggerExternalDocumentation) {
  'use strict';




  /**
   * The SwaggerTag model module.
   * @module DiscoverySearchEngine/DiscoverySearchEngine/SwaggerTag
   * @version v1
   */

  /**
   * Constructs a new <code>SwaggerTag</code>.
   * Describes a Swagger tag.
   * @alias module:DiscoverySearchEngine/DiscoverySearchEngine/SwaggerTag
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>SwaggerTag</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:DiscoverySearchEngine/DiscoverySearchEngine/SwaggerTag} obj Optional instance to populate.
   * @return {module:DiscoverySearchEngine/DiscoverySearchEngine/SwaggerTag} The populated <code>SwaggerTag</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('externalDocs')) {
        obj['externalDocs'] = SwaggerExternalDocumentation.constructFromObject(data['externalDocs']);
      }
    }
    return obj;
  }

  /**
   * Gets or sets the name.
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * Gets or sets the description.
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * Gets or sets the external documentation.
   * @member {module:DiscoverySearchEngine/DiscoverySearchEngine/SwaggerExternalDocumentation} externalDocs
   */
  exports.prototype['externalDocs'] = undefined;



  return exports;
}));


