/*
 * MASAI Service Discovery API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Rating range information
 */
@ApiModel(description = "Rating range information")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-07T16:09:20.617+01:00")
public class Rating {
  @SerializedName("minRating")
  private Float minRating = null;

  @SerializedName("maxRating")
  private Float maxRating = null;

  public Rating minRating(Float minRating) {
    this.minRating = minRating;
    return this;
  }

   /**
   * Minimum rating
   * @return minRating
  **/
  @ApiModelProperty(value = "Minimum rating")
  public Float getMinRating() {
    return minRating;
  }

  public void setMinRating(Float minRating) {
    this.minRating = minRating;
  }

  public Rating maxRating(Float maxRating) {
    this.maxRating = maxRating;
    return this;
  }

   /**
   * Maximum rating
   * @return maxRating
  **/
  @ApiModelProperty(value = "Maximum rating")
  public Float getMaxRating() {
    return maxRating;
  }

  public void setMaxRating(Float maxRating) {
    this.maxRating = maxRating;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Rating rating = (Rating) o;
    return Objects.equals(this.minRating, rating.minRating) &&
        Objects.equals(this.maxRating, rating.maxRating);
  }

  @Override
  public int hashCode() {
    return Objects.hash(minRating, maxRating);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Rating {\n");
    
    sb.append("    minRating: ").append(toIndentedString(minRating)).append("\n");
    sb.append("    maxRating: ").append(toIndentedString(maxRating)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

