/*
 * MASAI Service Discovery API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Data;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * SearchResponse
 */
@ApiModel(description = "SearchResponse")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-07T16:09:20.617+01:00")
public class SearchResponse {
  @SerializedName("serviceDescription")
  private List<Data> serviceDescription = null;

  @SerializedName("timers")
  private List<String> timers = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("message")
  private String message = null;

  public SearchResponse serviceDescription(List<Data> serviceDescription) {
    this.serviceDescription = serviceDescription;
    return this;
  }

  public SearchResponse addServiceDescriptionItem(Data serviceDescriptionItem) {
    if (this.serviceDescription == null) {
      this.serviceDescription = new ArrayList<Data>();
    }
    this.serviceDescription.add(serviceDescriptionItem);
    return this;
  }

   /**
   * Service information
   * @return serviceDescription
  **/
  @ApiModelProperty(value = "Service information")
  public List<Data> getServiceDescription() {
    return serviceDescription;
  }

  public void setServiceDescription(List<Data> serviceDescription) {
    this.serviceDescription = serviceDescription;
  }

  public SearchResponse timers(List<String> timers) {
    this.timers = timers;
    return this;
  }

  public SearchResponse addTimersItem(String timersItem) {
    if (this.timers == null) {
      this.timers = new ArrayList<String>();
    }
    this.timers.add(timersItem);
    return this;
  }

   /**
   * Timer information for each search engine
   * @return timers
  **/
  @ApiModelProperty(value = "Timer information for each search engine")
  public List<String> getTimers() {
    return timers;
  }

  public void setTimers(List<String> timers) {
    this.timers = timers;
  }

  public SearchResponse status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Status information
   * @return status
  **/
  @ApiModelProperty(value = "Status information")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public SearchResponse message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Service error message
   * @return message
  **/
  @ApiModelProperty(value = "Service error message")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchResponse searchResponse = (SearchResponse) o;
    return Objects.equals(this.serviceDescription, searchResponse.serviceDescription) &&
        Objects.equals(this.timers, searchResponse.timers) &&
        Objects.equals(this.status, searchResponse.status) &&
        Objects.equals(this.message, searchResponse.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(serviceDescription, timers, status, message);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchResponse {\n");
    
    sb.append("    serviceDescription: ").append(toIndentedString(serviceDescription)).append("\n");
    sb.append("    timers: ").append(toIndentedString(timers)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

