/*
 * MASAI Service Discovery API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.DiscoveryRequest;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Search request object
 */
@ApiModel(description = "Search request object")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-07T16:09:20.617+01:00")
public class SearchCriteria {
  /**
   * Environment to search services
   */
  @JsonAdapter(EnvironmentEnum.Adapter.class)
  public enum EnvironmentEnum {
    SANDBOX("SANDBOX"),
    
    PRODUCTION("PRODUCTION");

    private String value;

    EnvironmentEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static EnvironmentEnum fromValue(String text) {
      for (EnvironmentEnum b : EnvironmentEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<EnvironmentEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final EnvironmentEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public EnvironmentEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return EnvironmentEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("environment")
  private EnvironmentEnum environment = null;

  @SerializedName("serviceSearchCriteria")
  private List<DiscoveryRequest> serviceSearchCriteria = new ArrayList<DiscoveryRequest>();

  public SearchCriteria environment(EnvironmentEnum environment) {
    this.environment = environment;
    return this;
  }

   /**
   * Environment to search services
   * @return environment
  **/
  @ApiModelProperty(required = true, value = "Environment to search services")
  public EnvironmentEnum getEnvironment() {
    return environment;
  }

  public void setEnvironment(EnvironmentEnum environment) {
    this.environment = environment;
  }

  public SearchCriteria serviceSearchCriteria(List<DiscoveryRequest> serviceSearchCriteria) {
    this.serviceSearchCriteria = serviceSearchCriteria;
    return this;
  }

  public SearchCriteria addServiceSearchCriteriaItem(DiscoveryRequest serviceSearchCriteriaItem) {
    this.serviceSearchCriteria.add(serviceSearchCriteriaItem);
    return this;
  }

   /**
   * List containing each type of service to look for
   * @return serviceSearchCriteria
  **/
  @ApiModelProperty(required = true, value = "List containing each type of service to look for")
  public List<DiscoveryRequest> getServiceSearchCriteria() {
    return serviceSearchCriteria;
  }

  public void setServiceSearchCriteria(List<DiscoveryRequest> serviceSearchCriteria) {
    this.serviceSearchCriteria = serviceSearchCriteria;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchCriteria searchCriteria = (SearchCriteria) o;
    return Objects.equals(this.environment, searchCriteria.environment) &&
        Objects.equals(this.serviceSearchCriteria, searchCriteria.serviceSearchCriteria);
  }

  @Override
  public int hashCode() {
    return Objects.hash(environment, serviceSearchCriteria);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchCriteria {\n");
    
    sb.append("    environment: ").append(toIndentedString(environment)).append("\n");
    sb.append("    serviceSearchCriteria: ").append(toIndentedString(serviceSearchCriteria)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

