/**
 * MASAI Service Discovery API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['DiscoverySearchEngine/ApiClient', 'DiscoverySearchEngine/DiscoverySearchEngine/Contact', 'DiscoverySearchEngine/DiscoverySearchEngine/Data', 'DiscoverySearchEngine/DiscoverySearchEngine/DiscoveryRequest', 'DiscoverySearchEngine/DiscoverySearchEngine/DiscoveryRequestServiceType', 'DiscoverySearchEngine/DiscoverySearchEngine/JsonExpectedSchema', 'DiscoverySearchEngine/DiscoverySearchEngine/JsonSchema4', 'DiscoverySearchEngine/DiscoverySearchEngine/JsonXmlObject', 'DiscoverySearchEngine/DiscoverySearchEngine/Location', 'DiscoverySearchEngine/DiscoverySearchEngine/Maintainers', 'DiscoverySearchEngine/DiscoverySearchEngine/Price', 'DiscoverySearchEngine/DiscoverySearchEngine/Properties', 'DiscoverySearchEngine/DiscoverySearchEngine/Rating', 'DiscoverySearchEngine/DiscoverySearchEngine/SearchCriteria', 'DiscoverySearchEngine/DiscoverySearchEngine/SearchResponse', 'DiscoverySearchEngine/DiscoverySearchEngine/SearchResult', 'DiscoverySearchEngine/DiscoverySearchEngine/SwaggerContact', 'DiscoverySearchEngine/DiscoverySearchEngine/SwaggerDocument', 'DiscoverySearchEngine/DiscoverySearchEngine/SwaggerDocumentPaths', 'DiscoverySearchEngine/DiscoverySearchEngine/SwaggerExternalDocumentation', 'DiscoverySearchEngine/DiscoverySearchEngine/SwaggerInfo', 'DiscoverySearchEngine/DiscoverySearchEngine/SwaggerLicense', 'DiscoverySearchEngine/DiscoverySearchEngine/SwaggerOperation', 'DiscoverySearchEngine/DiscoverySearchEngine/SwaggerParameter', 'DiscoverySearchEngine/DiscoverySearchEngine/SwaggerResponse', 'DiscoverySearchEngine/DiscoverySearchEngine/SwaggerSecurityScheme', 'DiscoverySearchEngine/DiscoverySearchEngine/SwaggerTag', 'DiscoverySearchEngine/DiscoverySearchEngine/ApiApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./DiscoverySearchEngine/Contact'), require('./DiscoverySearchEngine/Data'), require('./DiscoverySearchEngine/DiscoveryRequest'), require('./DiscoverySearchEngine/DiscoveryRequestServiceType'), require('./DiscoverySearchEngine/JsonExpectedSchema'), require('./DiscoverySearchEngine/JsonSchema4'), require('./DiscoverySearchEngine/JsonXmlObject'), require('./DiscoverySearchEngine/Location'), require('./DiscoverySearchEngine/Maintainers'), require('./DiscoverySearchEngine/Price'), require('./DiscoverySearchEngine/Properties'), require('./DiscoverySearchEngine/Rating'), require('./DiscoverySearchEngine/SearchCriteria'), require('./DiscoverySearchEngine/SearchResponse'), require('./DiscoverySearchEngine/SearchResult'), require('./DiscoverySearchEngine/SwaggerContact'), require('./DiscoverySearchEngine/SwaggerDocument'), require('./DiscoverySearchEngine/SwaggerDocumentPaths'), require('./DiscoverySearchEngine/SwaggerExternalDocumentation'), require('./DiscoverySearchEngine/SwaggerInfo'), require('./DiscoverySearchEngine/SwaggerLicense'), require('./DiscoverySearchEngine/SwaggerOperation'), require('./DiscoverySearchEngine/SwaggerParameter'), require('./DiscoverySearchEngine/SwaggerResponse'), require('./DiscoverySearchEngine/SwaggerSecurityScheme'), require('./DiscoverySearchEngine/SwaggerTag'), require('./DiscoverySearchEngine/ApiApi'));
  }
}(function(ApiClient, Contact, Data, DiscoveryRequest, DiscoveryRequestServiceType, JsonExpectedSchema, JsonSchema4, JsonXmlObject, Location, Maintainers, Price, Properties, Rating, SearchCriteria, SearchResponse, SearchResult, SwaggerContact, SwaggerDocument, SwaggerDocumentPaths, SwaggerExternalDocumentation, SwaggerInfo, SwaggerLicense, SwaggerOperation, SwaggerParameter, SwaggerResponse, SwaggerSecurityScheme, SwaggerTag, ApiApi) {
  'use strict';

  /**
   * ERROR_UNKNOWN.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var DiscoverySearchEngine = require('DiscoverySearchEngine/index'); // See note below*.
   * var xxxSvc = new DiscoverySearchEngine.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new DiscoverySearchEngine.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['DiscoverySearchEngine/index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new DiscoverySearchEngine.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new DiscoverySearchEngine.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module DiscoverySearchEngine/index
   * @version v1
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:DiscoverySearchEngine/ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The Contact model constructor.
     * @property {module:DiscoverySearchEngine/DiscoverySearchEngine/Contact}
     */
    Contact: Contact,
    /**
     * The Data model constructor.
     * @property {module:DiscoverySearchEngine/DiscoverySearchEngine/Data}
     */
    Data: Data,
    /**
     * The DiscoveryRequest model constructor.
     * @property {module:DiscoverySearchEngine/DiscoverySearchEngine/DiscoveryRequest}
     */
    DiscoveryRequest: DiscoveryRequest,
    /**
     * The DiscoveryRequestServiceType model constructor.
     * @property {module:DiscoverySearchEngine/DiscoverySearchEngine/DiscoveryRequestServiceType}
     */
    DiscoveryRequestServiceType: DiscoveryRequestServiceType,
    /**
     * The JsonExpectedSchema model constructor.
     * @property {module:DiscoverySearchEngine/DiscoverySearchEngine/JsonExpectedSchema}
     */
    JsonExpectedSchema: JsonExpectedSchema,
    /**
     * The JsonSchema4 model constructor.
     * @property {module:DiscoverySearchEngine/DiscoverySearchEngine/JsonSchema4}
     */
    JsonSchema4: JsonSchema4,
    /**
     * The JsonXmlObject model constructor.
     * @property {module:DiscoverySearchEngine/DiscoverySearchEngine/JsonXmlObject}
     */
    JsonXmlObject: JsonXmlObject,
    /**
     * The Location model constructor.
     * @property {module:DiscoverySearchEngine/DiscoverySearchEngine/Location}
     */
    Location: Location,
    /**
     * The Maintainers model constructor.
     * @property {module:DiscoverySearchEngine/DiscoverySearchEngine/Maintainers}
     */
    Maintainers: Maintainers,
    /**
     * The Price model constructor.
     * @property {module:DiscoverySearchEngine/DiscoverySearchEngine/Price}
     */
    Price: Price,
    /**
     * The Properties model constructor.
     * @property {module:DiscoverySearchEngine/DiscoverySearchEngine/Properties}
     */
    Properties: Properties,
    /**
     * The Rating model constructor.
     * @property {module:DiscoverySearchEngine/DiscoverySearchEngine/Rating}
     */
    Rating: Rating,
    /**
     * The SearchCriteria model constructor.
     * @property {module:DiscoverySearchEngine/DiscoverySearchEngine/SearchCriteria}
     */
    SearchCriteria: SearchCriteria,
    /**
     * The SearchResponse model constructor.
     * @property {module:DiscoverySearchEngine/DiscoverySearchEngine/SearchResponse}
     */
    SearchResponse: SearchResponse,
    /**
     * The SearchResult model constructor.
     * @property {module:DiscoverySearchEngine/DiscoverySearchEngine/SearchResult}
     */
    SearchResult: SearchResult,
    /**
     * The SwaggerContact model constructor.
     * @property {module:DiscoverySearchEngine/DiscoverySearchEngine/SwaggerContact}
     */
    SwaggerContact: SwaggerContact,
    /**
     * The SwaggerDocument model constructor.
     * @property {module:DiscoverySearchEngine/DiscoverySearchEngine/SwaggerDocument}
     */
    SwaggerDocument: SwaggerDocument,
    /**
     * The SwaggerDocumentPaths model constructor.
     * @property {module:DiscoverySearchEngine/DiscoverySearchEngine/SwaggerDocumentPaths}
     */
    SwaggerDocumentPaths: SwaggerDocumentPaths,
    /**
     * The SwaggerExternalDocumentation model constructor.
     * @property {module:DiscoverySearchEngine/DiscoverySearchEngine/SwaggerExternalDocumentation}
     */
    SwaggerExternalDocumentation: SwaggerExternalDocumentation,
    /**
     * The SwaggerInfo model constructor.
     * @property {module:DiscoverySearchEngine/DiscoverySearchEngine/SwaggerInfo}
     */
    SwaggerInfo: SwaggerInfo,
    /**
     * The SwaggerLicense model constructor.
     * @property {module:DiscoverySearchEngine/DiscoverySearchEngine/SwaggerLicense}
     */
    SwaggerLicense: SwaggerLicense,
    /**
     * The SwaggerOperation model constructor.
     * @property {module:DiscoverySearchEngine/DiscoverySearchEngine/SwaggerOperation}
     */
    SwaggerOperation: SwaggerOperation,
    /**
     * The SwaggerParameter model constructor.
     * @property {module:DiscoverySearchEngine/DiscoverySearchEngine/SwaggerParameter}
     */
    SwaggerParameter: SwaggerParameter,
    /**
     * The SwaggerResponse model constructor.
     * @property {module:DiscoverySearchEngine/DiscoverySearchEngine/SwaggerResponse}
     */
    SwaggerResponse: SwaggerResponse,
    /**
     * The SwaggerSecurityScheme model constructor.
     * @property {module:DiscoverySearchEngine/DiscoverySearchEngine/SwaggerSecurityScheme}
     */
    SwaggerSecurityScheme: SwaggerSecurityScheme,
    /**
     * The SwaggerTag model constructor.
     * @property {module:DiscoverySearchEngine/DiscoverySearchEngine/SwaggerTag}
     */
    SwaggerTag: SwaggerTag,
    /**
     * The ApiApi service constructor.
     * @property {module:DiscoverySearchEngine/DiscoverySearchEngine/ApiApi}
     */
    ApiApi: ApiApi
  };

  return exports;
}));
